plugins {
    id "com.android.library"
}

def compileSdkValue = providers.gradleProperty("android.compileSdk").orElse("35").get().toInteger()
def minSdkValue = providers.gradleProperty("android.minSdk").orElse("26").get().toInteger()

android {
    namespace "com.fz.blelib"
    compileSdk compileSdkValue

    defaultConfig {
        minSdk minSdkValue
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
