#!/usr/bin/env python3
import math
import os
import shutil
import struct
import sys
import wave


SAMPLE_RATE = 48000
SECONDS = 4
PIECES = 10
FIXTURE_MARKER = ".music_analyzer_generated_urmp_fixture"
INSTRUMENTS = (
    ("bs", 43),
    ("as", 55),
    ("cl", 60),
    ("vn", 67),
)
WINDOWS = (
    (0.25, 0.62, (0, 4, 7, 12)),
    (1.05, 0.62, (5, 9, 12, 17)),
    (1.85, 0.62, (9, 12, 16, 21)),
    (2.65, 0.62, (7, 11, 14, 19)),
)


def midi_frequency(midi):
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def midi_at_or_above(min_midi, pitch_class):
    return min_midi + ((pitch_class - min_midi % 12 + 12) % 12)


def harmonic_sample(midi, amp, index, profile):
    value = 0.0
    for harmonic, scale in profile:
        value += (
            amp
            * scale
            * math.sin(
                2.0
                * math.pi
                * midi_frequency(midi)
                * harmonic
                * index
                / SAMPLE_RATE
            )
        )
    return value


def instrument_profile(instrument):
    if instrument == "vn":
        return ((1, 1.0), (2, 0.35), (3, 0.28), (4, 0.18), (5, 0.08))
    if instrument == "cl":
        return ((1, 1.0), (3, 0.38), (5, 0.16), (7, 0.08))
    if instrument == "as":
        return ((1, 1.0), (2, 0.24), (3, 0.32), (4, 0.10), (5, 0.08))
    return ((1, 1.0), (2, 0.45), (3, 0.16), (4, 0.12))


def write_wav(path, channels):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    frames = bytearray()
    for index in range(SAMPLE_RATE * SECONDS):
        value = sum(channel[index] for channel in channels)
        value = max(-0.95, min(0.95, value))
        frames.extend(struct.pack("<h", int(value * 32767.0)))

    with wave.open(path, "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        wav.writeframes(bytes(frames))


def write_piece(root, index):
    root_pitch_class = (index * 5) % 12
    piece_name = f"Bach10_{index:02d}_bs_as_cl_vn"
    piece_dir = os.path.join(root, piece_name)
    os.makedirs(piece_dir, exist_ok=True)

    parts = []
    for track_index, (instrument, floor) in enumerate(INSTRUMENTS, start=1):
        channel = [0.0 for _ in range(SAMPLE_RATE * SECONDS)]
        note_rows = []
        profile = instrument_profile(instrument)
        for onset, duration, intervals in WINDOWS:
            pitch_class = (root_pitch_class + intervals[track_index - 1]) % 12
            midi = midi_at_or_above(floor, pitch_class)
            start = int(onset * SAMPLE_RATE)
            end = int((onset + duration) * SAMPLE_RATE)
            for sample_index in range(start, min(end, len(channel))):
                rel = (sample_index - start) / max(1, end - start)
                envelope = min(1.0, rel * 18.0) * (1.0 - 0.18 * rel)
                channel[sample_index] += harmonic_sample(midi, 0.105 * envelope, sample_index, profile)
            note_rows.append((onset, duration, midi))
        parts.append(channel)

        write_wav(
            os.path.join(piece_dir, f"AuSep_{track_index}_{instrument}_{index:02d}_Bach10.wav"),
            [channel],
        )
        with open(
            os.path.join(piece_dir, f"Notes_{track_index}_{instrument}_{index:02d}_Bach10.txt"),
            "w",
            encoding="utf-8",
        ) as notes_file:
            for onset, duration, midi in note_rows:
                notes_file.write(f"{onset:.3f} {midi_frequency(midi):.6f} {duration:.3f}\n")

    write_wav(os.path.join(piece_dir, f"AuMix_{index:02d}_Bach10_bs_as_cl_vn.wav"), parts)


def main(argv):
    if len(argv) != 2:
        print("usage: generate_bach10_fixture.py OUTPUT_DIR", file=sys.stderr)
        return 2

    output_dir = argv[1]
    shutil.rmtree(output_dir, ignore_errors=True)
    os.makedirs(output_dir)
    with open(os.path.join(output_dir, FIXTURE_MARKER), "w", encoding="utf-8") as marker:
        marker.write("generated by tests/generate_bach10_fixture.py\n")

    for index in range(1, PIECES + 1):
        write_piece(output_dir, index)
    print(f"generate_bach10_fixture: wrote {PIECES} Bach10-style pieces to {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
