#!/bin/sh
set -eu

exec env \
    MUSIC_ANALYZER_REAL_NOTE_SAMPLES_REQUIRED=1 \
    MUSIC_ANALYZER_REAL_NOTE_FULL_MIX=1 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_BASS=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_GUITAR=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_PIANO=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_VOCALS=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_OTHER=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_ANY_HIT_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_FIRST_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_BASS_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_GUITAR_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_PIANO_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_VOCALS_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MIN_OTHER_EXPECTED_ROW_PERCENT=0 \
    MUSIC_ANALYZER_REAL_NOTE_MAX_DRUM_ACTIVE_PERCENT=100 \
    MUSIC_ANALYZER_REAL_NOTE_MAX_FAILURES=999999 \
    MUSIC_ANALYZER_REAL_NOTE_VERBOSE_DRUMS=1 \
    MUSIC_ANALYZER_REAL_NOTE_VERBOSE_DRUM_LIMIT=24 \
    build/analyzer_real_note_samples
