#!/bin/sh
set -eu

exec env \
    MUSIC_ANALYZER_DRUM_SAMPLES_REQUIRED=1 \
    MUSIC_ANALYZER_DRUM_SAMPLE_REQUIRED_CATEGORIES=hihat \
    MUSIC_ANALYZER_DRUM_SAMPLE_FILTER_CATEGORY=hihat \
    MUSIC_ANALYZER_DRUM_SAMPLES_DIR=build/hf_drum_kit_samples \
    MUSIC_ANALYZER_DRUM_SAMPLE_MIN_RECALL_PERCENT=0 \
    MUSIC_ANALYZER_DRUM_SAMPLE_MIN_PRECISION_PERCENT=0 \
    MUSIC_ANALYZER_DRUM_SAMPLE_MIN_PRIMARY_RECALL_PERCENT=0 \
    MUSIC_ANALYZER_DRUM_SAMPLE_MAX_KICK_FALSE_PERCENT=100 \
    MUSIC_ANALYZER_DRUM_SAMPLE_VERBOSE_ALL=1 \
    MUSIC_ANALYZER_DRUM_SAMPLE_VERBOSE_PRIMARY_LIMIT=20 \
    build/analyzer_drum_samples
